default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: syary_syary_development

test:
  <<: *default
  database: syary_syary_test

production:
  <<: *default
  database: syary_syary_production
  username: syary_syary
  password: <%= ENV['SYARY_SYARY_DATABASE_PASSWORD'] %>
